# Generated by Django 2.2.2 on 2020-08-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='date updated'),
        ),
    ]
