# Generated by Django 2.2.2 on 2020-08-31 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=60, null=True)),
                ('slug', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('bg_pic', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devsworld', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('website_url_type', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('phone_type', models.CharField(blank=True, max_length=30, null=True)),
                ('github_username', models.CharField(blank=True, max_length=60, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('birthday', models.CharField(blank=True, max_length=40, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
