# Generated by Django 2.2.2 on 2020-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
