# Generated by Django 2.2.2 on 2020-08-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_remove_experience_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='country',
        ),
    ]
