# Generated by Django 2.2.2 on 2020-08-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20200817_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
