# Generated by Django 2.2.2 on 2020-08-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_auto_20200826_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
