# Generated by Django 2.2.2 on 2020-08-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_auto_20200826_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
